name: "Full App CI (Front & Back) with SonarCloud"

on:
  push:
    branches:
      - main
    paths:
      - 'simple-website/**' 
      - '.github/workflows/**'
      - 'k8s/**'
  pull_request:
    branches:
      - main
    paths:
      - 'simple-website/**'
      - '.github/workflows/**'

jobs:
  sonar-analysis:
    name: "SonarCloud Analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        with:
          args: >
            -Dsonar.projectKey=karimwa323_Cloud-native-end-to-end
            -Dsonar.organization=karimovic
            -Dsonar.sources=simple-website/

  build-and-push:
    name: "Build & Push Images"
    needs: sonar-analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - component: "frontend"
            repo_name: "cloud-native-app"
            dockerfile_path: "./simple-website/frontend/Dockerfile"
            context: "./simple-website/frontend"
          - component: "backend"
            repo_name: "cloud-native-backend" 
            dockerfile_path: "./simple-website/backend/Dockerfile"
            context: "./simple-website/backend"

    steps:
      - uses: actions/checkout@v4

      - name: Build ${{ matrix.component }} Image
        run: |
          docker build -t ${{ matrix.component }}:${{ github.run_id }} -f ${{ matrix.dockerfile_path }} ${{ matrix.context }}

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ matrix.component }}:${{ github.run_id }}'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1

      - name: Push ${{ matrix.component }} to ECR
        run: |
          docker tag ${{ matrix.component }}:${{ github.run_id }} ${{ steps.login-ecr.outputs.registry }}/${{ matrix.repo_name }}:${{ github.run_id }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ matrix.repo_name }}:${{ github.run_id }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region eu-central-1 --name cloud-native-eks-prod
      
      - name: Deploy to EKS
        run: |
          sed -i "s|image:.*frontend:.*|image: ${{ steps.login-ecr.outputs.registry }}/cloud-native-frontend:${{ github.run_id }}|g" k8s/frontend-deployment.yaml
          sed -i "s|image:.*backend:.*|image: 010438480291.dkr.ecr.eu-central-1.amazonaws.com/cloud-native-backend:${{ github.run_id }}|g" k8s/backend-deployment.yaml

          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/backend-deployment.yaml